PROJECT = erlang
PROJECT_DESCRIPTION = New project
PROJECT_VERSION = 0.1.0

DEPS = cowboy jsx eredis uuid
dep_cowboyw_commit = 2.12.0
dep_jsx = git https://github.com/talentdeficit/jsx#encoder3-decoder3--parser
dep_eredis = git https://github.com/wooga/eredis.git
dep_uuid = git https://github.com/avtobiff/erlang-uuid.git

DEP_PLUGINS = cowboy jsx eredis uuid

REL_DEPS += relx
include erlang.mk
