PROJECT = erlang
PROJECT_DESCRIPTION = New project
PROJECT_VERSION = 0.1.0

DEPS = cowboy jiffy jsx eredis
dep_cowboyw_commit = 2.12.0

DEP_PLUGINS = cowboy jiffy jsx eredis

dep_jiffy = git https://github.com/davisp/jiffy
dep_jsx = git https://github.com/talentdeficit/jsx#encoder3-decoder3--parser
dep_eredis = git https://github.com/wooga/eredis.git

REL_DEPS += relx
include erlang.mk
